### ISSUE TITLE
3주차 Merge Issue

### ISSUE THREAD

**Issue by noojmogstel** [kakao-tech-campus-2nd-step3/Team4_BE#10]
### 병합시 생긴 문제

- Header에 토큰이 필요한 API에서 토큰 파싱 방법이 각자 달랐던 점을 통일해야함.

### 해결 방안

- Token이 필요한 요청에서 @RequestHeader 어노테이션으로 token을 받아 Service Layer에 같이 옮겨줌.

- 또 다른 방법이였던 MethodArgumentResolver는 추후 기능개선, 최적화 시 적용하기로 함.

**Comment by GamJaDo** [comment]
네 확인했습니다.

**Comment by chris0825** [comment]
확인했습니다.
