### ISSUE TITLE
Pt-API 엔드포인트 수정 및 Schedule-API로 일부 기능 분리 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#17]
### 현재 상황
![image](https://github.com/user-attachments/assets/72435dc7-c91c-4019-af2a-3da670c80435)
1. 진행중 PT의 상세 정보를 받아오는 엔드포인트가 `/api/pt/{user_id}`으로 정의됨
2. 스케쥴 조작 기능의 엔드포인트가 `/api/pt/{schedule_id}`으로 정의됨

### 건의 사항
1. 진행중 PT의 상세 정보를 받아오는 엔드포인트를 `/api/pt/{onGoingPt_id}`로 변경 건의
2. 스케쥴 조작 기능의 엔드포인트를 `/api/pt/schedule`로 시작하도록 변경하고 이를 Pt-API에서 Schedule-API로 분리하는 것을 건의

### 사유
1. PT를 진행중인 회원의 정보가 아닌 진행중인 PT정보를 `user_id`로 접근하는 것은 옳지 않다고 생각됨
2. ERD상으로 Schedule테이블이 OnGoingPt.id를 참조하고, 이를 분리하면 서비스 레이어에서 각각의 레포지토리만 의존 주입하면 됨

**Comment by GamJaDo** [comment]
건의 사항 1, 2 그대로 반영해주세요
