### ISSUE TITLE
CustomException 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#18]
### 현재 상황
![image](https://github.com/user-attachments/assets/6db2542d-7af9-4a93-bccd-291efbe10d8d)
- NotFound***Exception으로 중복된 CustomExcpetion파일 존재
- Exception message를 문자열의 형태로 전달

### 건의 사항
- NotFound***Exception -> NotFoundException으로 통합 건의
- Exception message 상수화 건의

### 사유
- 중복된 의미의 CustomException들을 하나로 합치는 것이 바람직해 보임
- Custom Exception 발생마다 문자열의 형태로 전달하는것 보다 Exception Message를 상수화시켜 한곳에서 관리하는것이 유지보수에 용이하다고 생각

**Comment by GamJaDo** [comment]
확인했습니다.
