### ISSUE TITLE
리뷰 테이블 속성 변경 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#19]
### 현재 상태
![image](https://github.com/user-attachments/assets/2d132195-ad46-49f5-9615-63b3ff962219)
- 리뷰 테이블이 트레이너와 일반회원의 ID를 FK로 참조

### 건의 사항
- 리뷰 테이블이 트레이너와 진행중인 PT ID를 FK로 참조하도록 변경 건의

### 사유
- 리뷰에서 작성자를 익명으로 처리할 예정이고, 진행중인 PT가 75%이상 진행되면 리뷰 작성을 가능하게 할 것이므로 진행중인 PT와 연결하는 것이 더 맞다고 판단함.
- 일반회원에게는 리뷰를 한번 작성하면 수정할 수 없다고 고지하면 됨
- 일반회원은 본인이 작성한 리뷰를 굳이 다시 확인할 필요가 없다고 판단
- 리뷰에 작성자의 정보 대신 구매한 상품(PT)에 대한 정보를 노출하면 좋을 것 같다고 판단

**Comment by GamJaDo** [comment]
확인했습니다.
