### ISSUE TITLE
제안 목록 테이블과 진행중인 PT 테이블의 통합 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#23]
### 현재 상황
- 제안 목록(id, user_id, trainer_id, status, count, price)
- 진행중인 PT(id, user_id, trainer_id, count, start_date)

### 건의 상황
- 진행중인 PT테이블을 삭제하는 것을 건의(이로 인한 스케쥴 테이블은 제안 목록의 id를 참조하도록 변경)
- 제안 목록 테이블의 이름을 PT 테이블로 이름 변경 건의

### 사유
- 진행중인 PT 테이블이 결국 제안 목록의 애트리뷰트 중에서 status가 진행중인 것들을 필터링한 결과를 모아놓은 중복된 데이터라 판단
- 추후 제안 목록의 데이터가 많아진다면 id를 auto_increase대신에 규칙을 정해(짝수/홀수 또는 기타 방법) 그 부분에 대해서 인덱싱 서치를 하면 될 것 같다고 판단

**Comment by GamJaDo** [comment]
확인했습니다. 합쳐주시고 그대로 erd 반영해주세요

**Comment by chris0825** [comment]
![image](https://github.com/user-attachments/assets/ad7387c6-4513-4877-8d51-5c8d9d1bc723)
반영했습니다.
