### ISSUE TITLE
DTO(Request, Response) Record Type으로 변경

### ISSUE THREAD

**Issue by noojmogstel** [kakao-tech-campus-2nd-step3/Team4_BE#25]
### 내용
- 코드리뷰 관련 멘토님 피드백 수용
### 중요도
하
### 🎸
- Record 클래스 특징
  - final 클래스이므로 다른 클래스를 상속하거나/상속시킬 수 없습니다.
  - 자동생성 accessor 함수는 인스턴스 멤버 변수의 이름과 동일합니다.
  - Record 클래스의 접근제어자는 public, package-private 만 가능합니다.
  - Record 생성자의 접근제어자는 클래스의 접근제어자보다 제한된 수준이어서는 안됩니다.
- DTO 클래스에 record클래스가 적합한 이유
  - 단순하게 데이터를 한쪽에서 다른 한쪽으로 전달하기 위해서만 사용되는 데이터 전송 객체(혹은 DTO)를 생각해봅시다.
이런 객체를 사용하는 이유는 다양한 집계 연산을 수행한 후의 결과를 담아두거나, 외부 시스템과 통신 시에 필요하지 않은 데이터를 제거하여 대역폭 사용량을 줄이기 위해, 세부 구현을 노출시키지 않기 위해서, 혹은 변경되지 말아야 하는 API 설계 상의 이유 등 다양한 이유가 있을 수 있습니다.

**Comment by GamJaDo** [comment]
목요일 전까지 반영하겠습니다.

**Comment by GamJaDo** [comment]
반영 완료했습니다!!
