### ISSUE TITLE
내가 쓴 / 내가 받은 리뷰 조회 API 수정

### ISSUE THREAD

**Issue by noojmogstel** [kakao-tech-campus-2nd-step3/Team4_BE#28]
###  내용
현재 api/reviews GET 요청에서 트레이너 토큰으로 요청시 본인이 받은 리뷰, 일반회원 토큰으로 요청시 본인이 작성한 리뷰를 조회하게 되어있는데, 토큰검증시 트레이너, 유저를 구분하는 방법이 있다면 문제가 없지만 현재 없는걸로 알고있어서 API분리 요청함.
예시>
 - api/reviews/trainer -> 트레이너 본인이 받은 리뷰 모두 조회
 - api/reviews/user -> 일반회원 본인이 작성한 리뷰 모두 조회

### 중요도
하
### 🎸
다른 좋은 방법 있으면 제시해주세요~!

**Comment by GamJaDo** [comment]
분리하는 방법은 있습니다. 현재 토큰에는 id만 넣었는데 그거 말고 email을 넣는 겁니다. 그러면 해당 email이 유저 테이블에 없으면 트레이너고, 있으면 유저라고 판단할 수 있습니다. -> 더 좋은 방법이 있는지는 생각해 봐야 할 것 같습니다.

그리고 일반회원은 본인이 작성한 리뷰를 조회와 수정 삭제가 필요 없을 것 같다는 승현님 issues도 있습니다 #19 
확인 부탁드립니다.
