### ISSUE TITLE
Person테이블의 삭제 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#42]
### 현재 상황
- Person(id, email, password, name, profileImageUrl)
  - User(id, location)
  - Trainer(id, gym_id(FK), gender)

User extends Person
Trainer extends Person

### 건의 사항
- Person테이블의 상속 말고 User와 Trainer로 단독으로 존재하도록 변경을 건의
User(id, email, password, name, profileImageUrl)
Trainer(id, email, password, name, profileImageUrl, gym_id(FK), gender)

### 사유
- 상속의 이점을 살리지 못한다고 생각함
  - 메모리의 절약은 인정, 그러나 그 외 성능적인 부분에서 손해가 더 크다고 생각됨
  - 토큰을 파싱할때도 유저와 트레이너의 구분이 없다보니까 제공해야 할 서비스를 판단하는 로직이 추가됨
  - 새로운 기능을 추가시 유저와 트레이너의 그룹(성질)이 다르다보니 개발 과정에서 난관이 발생함
  - 가장 큰 이유로 유저와 트레이너의 성질이 전혀 같지 않음

**Comment by GamJaDo** [comment]
건의 사항 잘 읽었습니다. Person 테이블을 사용한 이유가 (일반 회원과 트레이너) 는 유저이기 때문에 공통된 속성을 기준으로 일반 회원과 트레이너를 만들어내는 형식으로 사용하려고 상속을 사용했던겁니다. 하지만 지금 규모로 보았을 때는 따로 나눠서 개발을 진행해도 무방하다고도 생각합니다. 하지만 성질이 다르다는것은 동의하기 어렵네요.

**Comment by GamJaDo** [comment]
그렇지만 나눠보도록 하겠습니다.

**Comment by chris0825** [comment]
설명을 조금 더 덧붙여보자면 제가 일반회원과 트레이너의 성질이 다르다고 말씀드렸던 이유는 일반 회원의 경우 진행중인 운동 서비스가 있는지의 여부에 따라 PT서비스 정보 제공 또는 매칭 서비스를 제공하게 되고, 트레이너의 경우 소속 헬스장에 따른 권한(헬스장 admin 기능)의 검증과 같이 두 서비스 사용자 간 공통적으로 제공되는 서비스가 존재하지 않아 둘의 토큰이 때문에 그렇게 말씀드렸던 것 같습니다!

**Comment by chris0825** [comment]
이러한 사유로 비록 동일한 필드에 대해 두 테이블로 분리하게 됐을 때 오히려 상속을 하는 이유가 될 수 있는 성능적인 측면에서 Person테이블을 상속하는 것이 아닌 독립적으로 존재했을 때 로직 하나가 줄어들게 되어 성능이 좋을 것으로 생각했습니다:)

**Comment by chris0825** [comment]
만약 그렇지 않다면 토큰에 트레이너와 일반 유저를 구분할 수 있는 항목과 GYM_id를 삽입하는 방법으로도 해결이 가능할 것으로 생각됩니다
