### ISSUE TITLE
토큰 정보 추가 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#43]
### 현재 상황
- 토큰 포함 정보(email, id, issueAt, expiration, secretKey)

### 건의 사항
- 토큰 포함 정보에 소속 gym_id 추가(소속된 gym이 없는 경우 null값이나 0 삽입)

### 사유
- 트레이너와 유저 테이블의 분리에 따른 jwt 토큰 발급 로직 분리 필요성 #42 
- 트레이너의 소속 헬스장 관리 방법에 따른 헬스장 admin 권한자의 승인(검증) 필요성 #41

**Comment by GamJaDo** [comment]
트레이너와 유저가 로그인 시 토큰을 발급하는 메서드를 분리하고, 트레이너의 토큰 발급시 gym_id도 넣자는 말씀이신건가요?
