### ISSUE TITLE
Preference에 BodyInfo.id외래키 추가 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#57]
### 현재 상황
- 선호 테이블에서 PT매칭 희망하는 일반 회원의 인바디 정보에 접근하려면 유저의 ID로 BodyInfo테이블에서 필터링해서 최종 인바디를 검색해야 함.

### 건의 사항
- Preference 테이블에 BodyInfo.id 외래키를 추가하기를 희망 (1:1)

### 사유
- 생각보다 인바디 정보에 접근할 경우가 많음. 따라서 성능 향상을 위해 이를 건의함.

[ 해당 상황 ]
- 트레이너가 내 주변 회원 찾기(매칭 희망 회원 목록) 렌더링할 때
- PT매칭 시작 시(선호 등록 시)

**Comment by GamJaDo** [comment]
네 알겠습니다
