### ISSUE TITLE
Preference 삭제후 재등록 관련 문제

### ISSUE THREAD

**Issue by noojmogstel** [kakao-tech-campus-2nd-step3/Team4_BE#59]
### 현재 상황
- Preference 삭제 시 soft delete로 구현하게 되면 실제 데이터는 삭제되지 않음. 하지만 User와 Preference는 1대1 관계이기 때문에 추가적인 선호도 생성이 불가능함.
-  등록한 선호도로 PT가 매칭이 된다면 더이상 트레이너에게 요청을 받을 이유가 없으므로 삭제해야함.
- 서비스 특성상 선호도 수정, PT가 끝나면 재등록 시에 최초 1회 후에 추가적인 선호도가 등록이 고려됨.

### 해결 방법
1. preference는 hard delete로 구현
2. 선호도 삭제 후 재등록 시 기존 deleted=true 이던 컬럼의 데이터를 수정해서 사용.
3. 특정 조건을 만족할 때만 UNIQUE 제약 조건이 적용되도록 설정.

### 🎸
- 위 해결방법 3가지중 한가지 골라주세요.
- 개인적으로 선호도는 복구가 필요한 정보가 아니라고 생각함.

**Comment by chris0825** [comment]
저는 1번 방법이 좋은 것 같습니다!

2번 방법의 경우 선호을 등록시(PT 매칭 시작시) 데이터가 이전의 데이터와 연관이 없기 때문에 바람직하지 않은 것 같습니다

**Comment by GamJaDo** [comment]
1번으로 가시죠

**Comment by noojmogstel** [comment]
확인 감사합니다~
