### ISSUE TITLE
Default Value 처리방식

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#60]
### 현재 상황
- default프로필이 Client요청으로 들어옴

### 건의 사항
- default값은 Entity에 기본 값으로 설정해두는 것을 건의

### 사유
- default는 변하지 않는 상수값과도 같다 생각하여 값이 이동하기 보다 상수화시켜 관리하는 것이 바람직하다 생각.

**Comment by noojmogstel** [comment]
동의합니다~!

**Comment by GamJaDo** [comment]
그렇게 하도록 하겠습니다!
