### ISSUE TITLE
Resolver 적용

### ISSUE THREAD

**Issue by noojmogstel** [kakao-tech-campus-2nd-step3/Team4_BE#63]
authorization은 HTTP Header 스펙이라 최대한 Controller Layer에서 처리.
Service에서는 HTTP Protoocol에 최대한 의존하지 않게 계층형으로 코드 작성

https://github.com/kakao-tech-campus-2nd-step3/Team4_BE/pull/54#discussion_r1788927044

**Comment by GamJaDo** [comment]
저번에 trainer 때도 따로 어노테이션으로 만들어서 TrainerController에서 메서드 호출를 호출했는데 그 방식이 맞았네요
역시 명준님 bb
