### ISSUE TITLE
일반 회원과 트레이너 구분 방법

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#68]
### 현재 상황
- 트레이너와 일반 회원의 구분을 Controller단에서 EndPoint를 다르게하여 business logic을 다르게 가져감

### 건의 사항
1. Member Table(id, role)을 만들어 여기서 생성되는 id를 User와 Trainer ID로 사용
2. 토큰에 Role속성 삽입(parsing method 분리 필요)
3. ID 홀짝 발급
4. ID 첫번째에 Role 표시
5. ID 0~5,000,000,000,000,000,000까지는 일반회원 / 5,000,000,000,000,000,001부터는 트레이너
6. ID 일반유저는 양수, 트레이너는 음수 발급

### 고려사항
- 성능, 서비스 확장성

**Comment by chris0825** [comment]
#78
해당 내용과 관련된 생각 업로드

**Comment by noojmogstel** [comment]
2번으로 해결.

**Comment by noojmogstel** [comment]
2번으로 해결
