### ISSUE TITLE
회원 가입시 ProfileImage 제외 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#72]
### 현재 상황
- 회원 가입시 profile image도 함께 입력받음

### 건의 사항
- 가입 과정에는 서비스 이용에 필수적인 요소만 입력 받도록 설정하도록 건의
  - 일반회원(email, password, name, location)
  - 트레이너(email, password, name, gender)

### 사유
- 서비스 가입 과정에서는 필수 요소만 입력 받도록 설정하는 것이 서비스 사용자 측면에서 이득이라고 생각(과정이 많을수록 이용자는 귀찮아하고 이용률 저하로 이어질 수 있음)
- 회원 가입시 프로필 이미지 설정을 동시에 받는 서비스가 주변에 떠오르지 않음

**Comment by GamJaDo** [comment]
그럼 회원가입시 프로필 이미지는 디폴트 이미지로 따로 두고 나중에 프로필 수정시 이미지를 수정할 수 있도록 하겠습니다!

**Comment by noojmogstel** [comment]
로직 변경 완료. #83 참고

**Comment by GamJaDo** [comment]
프론트의 요청으로 요청 메세지 형식을 JSON -> FormData형식으로 임시 변경
회원 가입시에는 프로필 이미지가 무조건 default이미로 설정.
이후 시간 여유가 되면 요청 메세지 형식을 JSON으로 변경 예정.
