### ISSUE TITLE
TrainerResolver와 UserResolver를 하나의 Resolver로 통합 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#77]
### 현재 상황
- User와 Trainer의 Resolver가 각각 존재

### 건의 사항
- 두 Resolver를 통합하고 @Login애너테이션으로 통합

### 사유
- 토큰을 검증하고 토큰에 들어있는 id를 반환하는 같은 역할을 하는 resolver가 굳이 두개로 나뉘어 있는 이유를 모르겠음
- 토큰을 발급하는 방식이 User와 Trainer가 다른것도 아니고 두 사용자의 토큰에 담긴 정보 및 반환 정보가 동일한데 둘로 나눠야 하나라는 생각임

**Comment by GamJaDo** [comment]
중복 코드가 점점 줄어드는것 같아서 좋은것 같습니다 b

**Comment by noojmogstel** [comment]
음 처음에는 Resolver에서 Entity를 반환받는 방식으로 구현하려고 해서 구분했었는데, 권장되지 않는 방법이라는것을 알게되어서 그냥 id를 반환하는 것으로 고쳐서 구현했었습니다. 그렇게 되면서 굳이 나눠져야 되나 라는 생각을 하긴 했었는데, 일단 그전에는 유저든 트레이너든 Controller에서 authorzation 필드를 받아와서 사용했었는데, 구분하고 나니 Trainer 토큰이면 @LoginTrainer, User 토큰이면 @LoginUser로 개발하는 입장에서 구분하기 쉬웠고, 이번에 Swagger 추가하면서 구분되어있어서 작성하기 편하다 라고 느꼈었습니다.

추가로 토큰에 ROLE이 들어간다면, 토큰 검증과 동시에 ROLE이 일치하는지 같이 확인하는 등 2차검증이 필요할수도 있다고 생각합니다. 
코드의 중복성을 생각한다면 통합하는것도, 가독성과 확장성을 생각한다면 구분하는것도 두 의견 모두 좋습니다~!
