### ISSUE TITLE
JWT토큰 포함내용 건의

### ISSUE THREAD

**Issue by chris0825** [kakao-tech-campus-2nd-step3/Team4_BE#78]
### 현재 상황
- id, email, expirTime, secretKey 등이 토큰 내용으로 들어감

### 건의 사항
- email 대신 토큰 생성시 ENUM으로 관리되는 {TRAINER, USER}를 파라미터로 입력받도록 변경 요청

### 사유
- email은 토큰을 파싱해서 사용할 일이 없음(현재 id만 반환받음)
- email내용은 id를 통해 DB에서 찾을 수 있음
- 파라미터로 role을 받는다면 파싱할 때 받는 정보들로 DB에서 데이터를 찾을 때 어떤 테이블에서 찾아야하는지 로직을 통해 결정이 가능
- 만약 유일성이 걱정돼서 email이 들어간 것이라면 오히려 테이블 명과 id를 담는 것이 명확성 측면에서 더욱 unique하고 활용성도 높을 것 같다고 생각
- 추후 확장성 측면에서도 TRAINER와 비슷한 역할의 Service Provider성질을 띄는 ROLE이 추가될 경우에도 건의 내용이 더욱 유용할 것 같다고 생각

**Comment by GamJaDo** [comment]
테이블을 구분하기 위해서 넣는건가요?

**Comment by chris0825** [comment]
넵 궁극적인 목적은 그것이 맞습니다.
ENUM으로 Role이 들어간다면 id도 현재 email과 함께 쓰이는 것 보다 명확하게 사용될 수 있을것으로 예상됩니다

**Comment by GamJaDo** [comment]
6주차 리뷰에서 멘토님이 이 의견을 픽 안하셔도 이걸 반영하실건가요?

**Comment by chris0825** [comment]
에 아뇨,,? 이대로 할거다 라고 전달드리는게 아니라
제 생각은 이렇다 이 의견에 대해서 다른 분들은 어떻게 생각하시는지 궁금해서 여쭤보려고 이슈 올렸습니디

**Comment by GamJaDo** [comment]
네 알겠습니다!
저도 솔직히 저번 금요일에 회의때 이 의견 쪽이라 저도 찬성이긴합다

**Comment by noojmogstel** [comment]
저도 금요일 회의때 동의했던 의견이라 좋은것같네요. 일단 리뷰달리면 그거보고 결정해보죠!🤩

**Comment by GamJaDo** [comment]
건의 사항 반영 완료
