### ISSUE TITLE
3주차 - 로그아웃 기능에 대한 이슈

### ISSUE THREAD

**Issue by GamJaDo** [kakao-tech-campus-2nd-step3/Team4_BE#9]
Auth API를 구현하기 전에는 로그아웃 기능을 서버에서 구현 하기로 했었습니다.

![t2](https://github.com/user-attachments/assets/d63c000d-169e-4c65-90f5-03b790bfa815)
![t1](https://github.com/user-attachments/assets/27e146be-3311-4a9c-bc8f-8c6d2d950757)

그런데 찾아보니 JWT는 세션처럼 `session.invalidate();`하는 것이 아닌 
토큰을 그냥 클라이언트에서
```javac
function logout() {
    // localStorage에서 JWT 토큰 삭제
    localStorage.removeItem('token');
    alert('로그아웃되었습니다.');
    // 로그인 페이지로 리디렉션
    window.location.href = '/login';
}
```
이렇게 삭제하는것이 더 낫은 방법인것 같습니다.

따라서 로그아웃 기능은 서버에서 구현하지말고 클라이언트에서 구현하는게 좋을것 같습니다.

**Comment by seorinnn** [comment]
확인했습니다!
